### ISSUE TITLE
cleanScheme() 后，在服务提供者设置的 beforeSend() 也会被清空

### ISSUE THREAD

**Issue by wwp66650** [toplan/laravel-sms#100]
cleanScheme() 后，在服务提供者设置的 beforeSend() 也会被清空。查了半天原因为什么发送记录不写入数据表了哈

**Comment by toplan** [comment]
了解了，这个是phpsms的一个bug

**Comment by toplan** [comment]
https://github.com/toplan/phpsms/issues/97
