### ISSUE TITLE
能否加上阿里云和weimi.cc的代理器

### ISSUE THREAD

**Issue by cnshayo** [toplan/laravel-sms#118]
尤其是阿里云的短信，可以直接使用比大于要方便多了

**Comment by skys215** [comment]
同需要阿里云

**Comment by skys215** [comment]
我发现其实有阿里云的了，vendor:publish之后就能在配置文件里面看到
只是没写在readme里面而已

**Comment by toplan** [comment]
请关注这里
https://github.com/toplan/phpsms/pulls
https://github.com/toplan/phpsms/issues
