### ISSUE TITLE
config/laravel-sms.php里面有function回调，导致php artisan config:cache后程序500

### ISSUE THREAD

**Issue by terranc** [toplan/laravel-sms#119]
cache后的config为：
![image](https://cloud.githubusercontent.com/assets/224353/19435306/77f48ca2-949c-11e6-8c0d-b6950b4852e5.png)

只要去掉这一段，程序正常。google里说config目录下不能用未定义的函数，估计匿名函数也不可以用。
求完美解决方案。

**Comment by toplan** [comment]
这个问题还没找到解决方案，是在不行只有改为字符串了

**Comment by medz** [comment]
这个问题好解决～在配置里面的回掉，使用php的魔术方法`__invoke`即可解决～配置的地方只需要配置class name即可～然后程序回掉方法调的时候就可以把一个class当成一个function执行，这样就触发了`__invoke`魔术方法执行～ 这种原理在laravel和slim框架中经常使用～尤其是slim～几乎全部都是通过这种魔术方法得以对class的支持的～

**Comment by toplan** [comment]
已发布 [2.6.1](https://github.com/toplan/laravel-sms/releases/tag/2.6.1)
目前使用的是序列化闭包的方式解决

**Comment by ellisfan** [comment]
@toplan Class 'Toplan\Sms\SmsManger' not found 怎么解决呢？在laravel-sms.php中使用 `Toplan\Sms\SmsManger::closure($closure)` 方法对匿名函数进行配置
