### ISSUE TITLE
在一个用户没有获取短信的随便乱打验证码提交的时候，会抛出attempts未定义的异常

### ISSUE THREAD

**Issue by branchzero** [toplan/laravel-sms#122]
<img width="996" alt="qq20161202-0 2x" src="https://cloud.githubusercontent.com/assets/7685609/20832266/58cfee38-b8c4-11e6-9e15-24bf4eb14207.png">
也就是说，未初始化的号码直接调用验证规则获取状态的话，需要在之前进行合法性判断。

**Comment by branchzero** [comment]
补充：版本是2.5.1，可以的话我可以提交一个PR来修掉？

**Comment by peirenlei** [comment]
这个问题 ，我很久以前就跟作者提过多次啦，他到现在都没改

**Comment by toplan** [comment]
已更新2.5.2
