### ISSUE TITLE
下载laravel-sms出错

### ISSUE THREAD

**Issue by zzilcc** [toplan/laravel-sms#124]
为什么我下载laravel-sms的时候报错

![79 9t 7ji m t jqp1 i4aq](https://cloud.githubusercontent.com/assets/18416922/21182134/7b7375d2-c23c-11e6-9e7a-123405d2822f.png)

**Comment by medz** [comment]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: jeremeamia/SuperClosure[2.2.0, 2.3.0].
    - Can only install one of: jeremeamia/SuperClosure[2.3.0, 2.2.0].
    - Can only install one of: jeremeamia/SuperClosure[2.2.0, 2.3.0].
    - toplan/phpsms 1.6.0 requires jeremeamia/superclosure ~2.2.0 -> satisfiable by jeremeamia/SuperClosure[2.2.0].
    - toplan/laravel-sms 2.5.2 requires toplan/phpsms >=1.6.0 -> satisfiable by toplan/phpsms[1.6.0].
    - Installation request for toplan/laravel-sms 2.5.2 -> satisfiable by toplan/laravel-sms[2.5.2].
    - Installation request for jeremeamia/superclosure (locked at 2.3.0) -> satisfiable by jeremeamia/SuperClosure[2.3.0].


Installation failed, reverting ./composer.json to its original content.

包的依赖有版本冲突问题，laravel5.3

**Comment by toplan** [comment]
删掉composer.lock 删掉vendor 然后composer update

**Comment by medz** [comment]
@toplan 并不会解决问题～composer.lock应该从你的仓库里面山了～其次，使用场景是laravel5.3 我直接require也报错～

**Comment by medz** [comment]
@toplan 就是你的依赖信息有问题～看 https://github.com/medz/phpsms/blob/master/composer.json#L15
我更新了依赖版本号～就正常了～目前我的使用方法是fork你的库，自己修改了信息，然后发布component，再依赖进来使用～

**Comment by toplan** [comment]
@medz 是的，之前也注意到了，能否提交pull request?谢谢

**Comment by medz** [comment]
@toplan 好的～我在master对程序做了小修改，我fork到新的分支，提交pr给你～

**Comment by medz** [comment]
@toplan https://github.com/toplan/phpsms/pull/81 已经提交pr

**Comment by uniteweiwei** [comment]
问题根本没有解决,laravel5.1.33也会报同样的错,感觉就是依赖有问题,其他依赖包都下载了

**Comment by medz** [comment]
@uniteweiwei 那是因为作者还没有合并pr～

**Comment by uniteweiwei** [comment]
@medz 那请问现在暂时有什么好的解决方案了?

**Comment by medz** [comment]
@uniteweiwei 我目前的方法是fork作者的库，然后自己修正后发布版本～不过，我已经给作者提交pr了～所以我自己fork的版本发布也停止了～

**Comment by uniteweiwei** [comment]
解决方法:
1.删掉一下，composer.lock文件
2.在composer.json(require里面),加入"toplan/laravel-sms":"2.5.2"
3.在composer里面执行composer install

**Comment by medz** [comment]
上述的解决方法，是指仓库的修复方法，而不是使用者的方法～目前使用者还没发正常使用的～除非自己发布pack，等作者合并。

**Comment by medz** [comment]
https://github.com/toplan/phpsms/pull/81/files
只需要修改几个composer配置即可解决的
```json5

    "name": "toplan/phpsms",
    "description": "sms send library for php, support the main SMS service provider.",
    "license": "MIT",
 -  "version": "1.6.0",
    "keywords": ["sms", "php sms", "phpsms", "sms library for php"],
    "authors": [
      {
 @@ -13,7 +12,7 @@
    "require": {
      "php": ">=5.4.0",
      "toplan/task-balancer": ">=0.4.2",
 -    "jeremeamia/SuperClosure": "~2.2.0"
 +    "jeremeamia/SuperClosure": "^2.3"
    },
    "require-dev": {
      "phpunit/phpunit": "~4.0"
 @@ -36,6 +35,5 @@
      "classmap": [
        "tests/"
      ]
 -  },
 -  "minimum-stability" : "dev"
 +  }
  }
```

**Comment by skys215** [comment]
手动at作者 @toplan

**Comment by toplan** [comment]
@skys215 😄 额，最近赶工期额

**Comment by skys215** [comment]
好的，静候佳音。

**Comment by liuxingjun** [comment]
[https://github.com/toplan/laravel-sms/blob/master/composer.json](url)

**Comment by liuxingjun** [comment]
laravel-sms 依赖 phpsms 1.6.0 
phpsms 1.6.0 里面依赖的SuperClosure 是2.2.0
phpsms  master 的SuperClosure 才是2.3.0
其实把phpsms master 打上一个行的tags 然后在 laravel-sms 里依赖新的tags 就行了

**Comment by ThinkMe** [comment]
还没有解决啊唉。。。

**Comment by toplan** [comment]
已发布 [2.6.1](https://github.com/toplan/laravel-sms/releases/tag/2.6.1)
