### ISSUE TITLE
验证码短信发送时间间隔控制

### ISSUE THREAD

**Issue by iflamed** [toplan/laravel-sms#13]
https://github.com/toplan/laravel-sms/blob/master/src/Toplan/LaravelSms/SmsContorller.php#L94 

这个函数应该需要支持验证码等短信发送间隔控制。比如现在规定验证码短信发送间隔为1分钟。目前这个库里面看起来只用了前端js 来控制，容易出问题。

**Comment by toplan** [comment]
已更新 :smile:

**Comment by iflamed** [comment]
👍👍

2015-09-21 11:36 GMT+08:00 top lan <notifications@github.com>:
