### ISSUE TITLE
不兼容LA5.4吗?

### ISSUE THREAD

**Issue by spc324** [toplan/laravel-sms#133]
laravel 5.4 安装报错，是nikic/php-parser 版本太高了？
`[37;41mYour requirements could not be resolved to an installable set of packages.[39;49m

  Problem 1
    - Installation request for nikic/php-parser (locked at v3.0.5) -> satisfiable by nikic/php-parser[v3.0.5].
    - toplan/laravel-sms 2.5.0 requires toplan/phpsms >=1.6.0 -> satisfiable by toplan/phpsms[1.6.0].
    - toplan/laravel-sms 2.5.1 requires toplan/phpsms >=1.6.0 -> satisfiable by toplan/phpsms[1.6.0].
    - toplan/laravel-sms 2.5.2 requires toplan/phpsms >=1.6.0 -> satisfiable by toplan/phpsms[1.6.0].
    - toplan/phpsms 1.6.0 requires jeremeamia/superclosure ~2.2.0 -> satisfiable by jeremeamia/SuperClosure[2.2.0].
    - Conclusion: don't install jeremeamia/SuperClosure 2.2.0
    - Installation request for toplan/laravel-sms 2.5.* -> satisfiable by toplan/laravel-sms[2.5.0, 2.5.1, 2.5.2].`

**Comment by toplan** [comment]
这个phpsms的一个兼容性问题，phpsms明天会发版本处理

**Comment by spc324** [comment]
好的

**Comment by spc324** [comment]
@toplan 这个问题处理了吗

**Comment by skys215** [comment]
我临时改了一下，可以用skys215/laravel-sms 但是没有发布到packagist，需要自己添加git仓库地址
坐等作者修复

**Comment by toplan** [comment]
phpsms 1.7.0 修改了这些问题，目前在测试中

**Comment by toplan** [comment]
已发布 [2.6.1](https://github.com/toplan/laravel-sms/releases/tag/2.6.1)
