### ISSUE TITLE
  [Toplan\PhpSms\PhpSmsException]                                                                     Modify the dispatch scheme failed for [Log] agent, because the task system has already started.  

### ISSUE THREAD

**Issue by QylinFly** [toplan/laravel-sms#136]
[Toplan\PhpSms\PhpSmsException]                                                                  
  Modify the dispatch scheme failed for [Log] agent, because the task system has already started.

**Comment by toplan** [comment]
这个是laravel-sms的一个bug，可以暂时这样处理：
SmsManagerServiceProvider里面register方法里面的$this->initPhpSms()移动到boot方法里

然后等待我发布新版本更新这个bug...

**Comment by QylinFly** [comment]
赞

**Comment by QylinFly** [comment]
我用了稳定版本后，问题消失

**Comment by toplan** [comment]
@QylinFly 什么问题 😄

**Comment by toplan** [comment]
已发布 [2.6.1](https://github.com/toplan/laravel-sms/releases/tag/2.6.1)
