### ISSUE TITLE
能不能release个稳定版本？

### ISSUE THREAD

**Issue by zhuzhichao** [toplan/laravel-sms#14]
dev的话感觉不是太好，添加个版本便于包管理。谢谢了。

**Comment by toplan** [comment]
好的，你说的对 :+1:

**Comment by zhuzhichao** [comment]
你的这个包虽然添加了版本，但是composer官网没有最新的版本列表，是因为hook没弄好吗？

我这边 "toplan/laravel-sms": "~1.0.1", 就根本找不到包，还是只能通过 "toplan/laravel-sms": "dev-master" 来更新了

失败
![image](https://cloud.githubusercontent.com/assets/3017759/10037152/a6ec1dcc-61e4-11e5-9295-a4e8eed312f4.png)

成功
![image](https://cloud.githubusercontent.com/assets/3017759/10037173/e4ebb646-61e4-11e5-9f0c-58af6c787e29.png)


官网没有release的版本
![qq20150923-1 2x](https://cloud.githubusercontent.com/assets/3017759/10037165/c7cc76c2-61e4-11e5-9987-62f8a4ca2b3b.png)

**Comment by toplan** [comment]
composer上已经有稳定版本 :smile:
