### ISSUE TITLE
 Modify the dispatch scheme failed for [YunPian] agent, because the task sys     tem has already started.

### ISSUE THREAD

**Issue by wyu-prc** [toplan/laravel-sms#140]
更新到toplan/phpsms (1.7.0)，报错：
[Toplan\PhpSms\PhpSmsException]                                              
  Modify the dispatch scheme failed for [YunPian] agent, because the task sys  
  tem has already started.                                                     
                                                                               

Script php artisan optimize handling the post-update-cmd event returned with error code 1

**Comment by wyu-prc** [comment]
更新到toplan/laravel-sms (2.6.1)，报错：
[ErrorException]              
  Illegal offset type in unset

**Comment by kankaner** [comment]
同样的错误  @skys215

**Comment by skys215** [comment]
重复 #139 
已联系作者修改。

**Comment by kankaner** [comment]
thanks 更新到2.6.2能用了

**Comment by toplan** [comment]
已发布2.6.2解决问题，建议更新前清除下composer里phpsms的缓存
