### ISSUE TITLE
更新到2.6.2，Illegal offset type in unset

### ISSUE THREAD

**Issue by wyu-prc** [toplan/laravel-sms#144]
更新到2.6.2后仍然报错：
[ErrorException]              
  Illegal offset type in unset

**Comment by toplan** [comment]
你看下phpsms的版本是否更新到了1.7.1
如果没有，那清除下phpsms的composer缓存或者手动安装下phpsms1.7.1

**Comment by wyu-prc** [comment]
OK了，谢谢。phpsms的版本是否更新到1.7.1后问题解决
