### ISSUE TITLE
SUBMAIL 发送成功后有错误信息

### ISSUE THREAD

**Issue by zhuzhichao** [toplan/laravel-sms#15]
SUBMAIL 成功的时候没有返回 msg，导致发送信息后提示错误。

Undefined index: msg(30行)
/Path/To/WWW/vendor/toplan/laravel-sms/src/Toplan/LaravelSms/agents/SubMailAgent.php

以下是SUBMAIL官方提供的返回内容。

http://submail.cn/chs/documents/developer/t2f1J2
请求成功

{
      "status":"success"
      "send_id":"093c0a7df143c087d6cba9cdf0cf3738"
      "sms_credits":14197
}
请求失败

{
      "status":"error",
      "code":"1xx",
      "msg":"error message"
}

**Comment by zhuzhichao** [comment]
成功的情况下也没有code

**Comment by toplan** [comment]
嗯。了解了，这里可能是官方接口发送了变动，或则是以前这里就有问题。谢谢反馈，我马上更改。

**Comment by zhuzhichao** [comment]
谢谢了，回复挺快的！我先本地改了，领导着急，没有推PR。

**Comment by toplan** [comment]
已提交更新 :smile:

**Comment by zhuzhichao** [comment]
赞！！！太棒了

**Comment by toplan** [comment]
:smile: thanks for your support
