### ISSUE TITLE
多个短信模板该如何配置调用

### ISSUE THREAD

**Issue by felixjing** [toplan/laravel-sms#152]
云通讯设置了多个短信模板，注册验证码、修改密码验证码等等，之前只用到一个注册验证码，在laravel-sms里配置了
'templates' => [
        'YunTongXun' => '123456'
    ],
现在需要使用云通讯的其他模板，请问该如何配置调用？

**Comment by toplan** [comment]
可以参考下这里 https://github.com/toplan/laravel-sms/blob/master/src/config/laravel-sms.php#L99

**Comment by toplan** [comment]
利用闭包来进行配置，`templates` 闭包拥有的两个参数为：`$input`, `$type`。
其中`$input`是前端传递的所有参数，`$type`则是类型，表示是短信还是语言。更好理解的话，可以打印出来看看。

**Comment by felixjing** [comment]
ok 我试下 谢谢
