### ISSUE TITLE
服务端数据验证问题

### ISSUE THREAD

**Issue by shenxiaodaosanhua** [toplan/laravel-sms#158]
![image](https://user-images.githubusercontent.com/4246374/27508529-db343758-5919-11e7-8e47-a91780255994.png)
![image](https://user-images.githubusercontent.com/4246374/27508535-eaa76c3c-5919-11e7-9197-811e8ec57d14.png)
在做验证码校验的时候一只提示这个错误，不知道怎么解决？

**Comment by shenxiaodaosanhua** [comment]
使用的是api模式

**Comment by toplan** [comment]
api的记得加上access tokan哦，具体参考文档

**Comment by shenxiaodaosanhua** [comment]
![image](https://user-images.githubusercontent.com/4246374/27510584-ad38244a-5946-11e7-9491-5f00e94e2fee.png)
在URL加？还是在请求头上加？
智商不够，搞不懂了

**Comment by toplan** [comment]
https://github.com/toplan/laravel-sms/blob/master/README.md#2-access-token

都可以，看上面这个链接

**Comment by toplan** [comment]
你那个写法是可以的，但是要记到给每个请求都加上。或者放请求头里，方便点。

**Comment by shenxiaodaosanhua** [comment]
![image](https://user-images.githubusercontent.com/4246374/27510766-c1983dd6-594a-11e7-85a7-fe72ae8dd229.png)

查看源码的时候发现
![image](https://user-images.githubusercontent.com/4246374/27510781-e315535e-594a-11e7-9e29-2907bc098b63.png)
我把这里的routeAttributes改成route；现在可以了。
感谢！
