### ISSUE TITLE
包安装后提示重复的类名警告错误

### ISSUE THREAD

**Issue by zhuzhichao** [toplan/laravel-sms#16]
![image](https://cloud.githubusercontent.com/assets/3017759/10037215/8f9ab1a0-61e5-11e5-8b4f-1ddc4e259391.png)

迁移文件是否能放到 src/ 同级的目录，避免 composer 把迁移文件给加到 class_map 里面，导致警告错误。 😀

**Comment by toplan** [comment]
好的
