### ISSUE TITLE
Class 'PhpSms' not found

### ISSUE THREAD

**Issue by liuwei0514** [toplan/laravel-sms#178]
版本：    "toplan/laravel-sms": "dev-master",
在config/app.php文件中providers数组里加入：
`Toplan\PhpSms\PhpSmsServiceProvider::class,
Toplan\Sms\SmsManagerServiceProvider::class,`

执行 php artisan vendor:publish --provider="Toplan\PhpSms\PhpSmsServiceProvider"，报错 
Class 'PhpSms' not found

`
[2018-07-17 14:42:03] local.ERROR: Class 'PhpSms' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'PhpSms' not found at /var/www/xiushouji-api/vendor/toplan/laravel-sms/src/Toplan/LaravelSms/SmsManagerServiceProvider.php:60)
[stacktrace]
#0 /var/www/xiushouji-api/vendor/toplan/laravel-sms/src/Toplan/LaravelSms/SmsManagerServiceProvider.php(33): Toplan\\Sms\\SmsManagerServiceProvider->phpSms()
#1 [internal function]: Toplan\\Sms\\SmsManagerServiceProvider->boot()
#2 /var/www/xiushouji-api/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#3 /var/www/xiushouji-api/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#4 /var/www/xiushouji-api/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#5 /var/www/xiushouji-api/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#6 /var/www/xiushouji-api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(794): Illuminate\\Container\\Container->call(Array)
#7 /var/www/xiushouji-api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(777): Illuminate\\Foundation\\Application->bootProvider(Object(Toplan\\Sms\\SmsManagerServiceProvider))
#8 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(Toplan\\Sms\\SmsManagerServiceProvider), 16)
#9 /var/www/xiushouji-api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(778): array_walk(Array, Object(Closure))
#10 /var/www/xiushouji-api/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#11 /var/www/xiushouji-api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(206): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#12 /var/www/xiushouji-api/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(297): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#13 /var/www/xiushouji-api/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(120): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#14 /var/www/xiushouji-api/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#15 {main}
"} 
`

**Comment by skys215** [comment]
还需要在aliases那里加
