### ISSUE TITLE
云片模板问题

### ISSUE THREAD

**Issue by excitedcat** [toplan/laravel-sms#18]
云片已支持模板短信发送，详情如下：
//模板接口样例（不推荐。需要测试请将注释去掉。)
/* 以下代码块已被注释
    $apikey = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"; //请用自己的apikey代替
    $mobile = "xxxxxxxxxxx"; //请用自己的手机号代替
    $tpl_id = 1; //对应默认模板 【#company#】您的验证码是#code#
    $tpl_value = "#company#=云片网&#code#=1234";
    echo tpl_send_sms($apikey,$tpl_id, $tpl_value, $mobile);
*/
我看到你代码中并没有开发这个功能：
public function sendTemplateSms($tempId, $to, Array $data)
{
   return null;
}

**Comment by toplan** [comment]
已加入todo list
