### ISSUE TITLE
luosimao不支持批量发送API,不可以用逗号把收件人手机号分开

### ISSUE THREAD

**Issue by RichardFans** [toplan/laravel-sms#21]
做了点小改动,但感觉这样效率不高,希望toplan能够给出更好的方案
  public function sendContentSms($to, $content)
    {
        //因为Luosimao的签名必须放在最后，所以发送前需要检测签名位置
        //如果不是在最后，则调整至最后
        $content = trim($content);
        if ($content && !preg_match('/】$/', $content)) {
            preg_match('/【([0-9a-zA-Z\W]+)】/', $content, $matches);
            $content = str_replace($matches[0], '', $content) . $matches[0];
        }

        $url = 'https://sms-api.luosimao.com/v1/send.json';
        $apikey = $this->apikey;

        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, "$url");

        curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 30);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
        curl_setopt($ch, CURLOPT_HEADER, FALSE);

        curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
        curl_setopt($ch, CURLOPT_USERPWD, 'api:key-' . $apikey);

        curl_setopt($ch, CURLOPT_POST, TRUE);

        $phone_list = explode(',', $to);
        foreach ($phone_list as $phone) {
            $optData = [
                'mobile' => $phone,
                'message' => $content
            ];
            curl_setopt($ch, CURLOPT_POSTFIELDS, $optData);
            $res = curl_exec($ch);
        }

        curl_close($ch);

        $data = json_decode($res, true);
        if ($data['error'] == 0) {
            $this->result['success'] = true;
        }
        $this->result['info'] = $this->currentAgentName . ':' . $data['msg'] . "({$data['error']})";
        $this->result['code'] = $data['error'];
    }

**Comment by toplan** [comment]
下来我会研究下，已加入todo list。最近在升级laraval-sms到新版本，会有比较大的改进和变动，该优先级应该会靠后点点。

**Comment by RichardFans** [comment]
luosimao现在支持批量发送了，希望框架能够提供相应接口，毕竟调用一次http请求要比用队列调用n次要好
