### ISSUE TITLE
云片网络是不支持内容短信的啊

### ISSUE THREAD

**Issue by wndershow** [toplan/laravel-sms#22]
是不是搞错了，亲，云片网络是不支持内容短信的啊
Toplan\Sms\Sms::make(‘1’)->to('1828****349')->data(['12345', 5])->send();
我这样调的然后返回参数错误！？

**Comment by toplan** [comment]
发送内容短信是这样的：
Toplan\Sms\Sms::make()->to('1828****349')->content('短信内容')->send();
