### ISSUE TITLE
特殊情况

### ISSUE THREAD

**Issue by nsioo** [toplan/laravel-sms#23]
请问下 我用自定义的代理发送短信内容/使用云之讯发送语音，这种情况下怎样切换代理？！

**Comment by toplan** [comment]
你好，`laravel-sms`的目前版本确实还不好处理你说的问题，如果你急要需解决这个，可以看下[phpsms](https://github.com/toplan/phpsms)这个php短信发送库，`phpsms`可以非常轻松的解决你的需求。当然，如果你不急的话，请等待`laravel-sms`的2.0版本，目前正在着手v2版本的开发

**Comment by toplan** [comment]
@nsioo 你好，v2.0版本已经release，在2.0版本中，你可以这样来指定代理器发送短信／语音验证码：
```php
PhpSms::voice()->to()->agent('Ucpaas')->send()
```
