### ISSUE TITLE
[服务器端]合法性验证的问题

### ISSUE THREAD

**Issue by spc324** [toplan/laravel-sms#24]
[服务器端]合法性验证  在控制器需要引入什么文件吗？ 为什么我这边测试不成功呢

$validator = \Validator::make($request->all(), [
				'mobile'     => 'required|mobile_changed',
				'verifyCode' => 'required|verify_code|verify_rule:check_mobile_unique',
			//more...
		]);

		if ($validator->fails()) {
			//验证失败的话需要清除session数据，防止用户多次试错
			\SmsManager::forgetSmsDataFromSession();
			return redirect()->back()->withErrors($validator);
		}

不管输入什么都会报mobile_changed  verify_code  verify_rule这三个字段的错误消息

**Comment by toplan** [comment]
你好，能否贴上错误消息？

**Comment by spc324** [comment]
换了一种方式写 已经 没有问题了  谢谢

**Comment by kcersing** [comment]
也碰到了这个问题~纠结
