### ISSUE TITLE
2.0开发得怎么样了

### ISSUE THREAD

**Issue by hawkefly** [toplan/laravel-sms#26]
2.0开发得怎么样了，是不是已经可以用了。

**Comment by toplan** [comment]
你好，基础功能是基于phpsms的，是能使用的，目前在测试一些关于验证码模块的高级功能。建议目前不要使用在生产环境。v2.0会在下周基本定型。

**Comment by toplan** [comment]
@hawkefly  2.0.2 目前比较稳定了，可以正常使用。
