### ISSUE TITLE
vendor publish error

### ISSUE THREAD

**Issue by hawkefly** [toplan/laravel-sms#27]
> /Applications/XAMPP/xamppfiles/bin/php /Users/liwei/Documents/dev/huifeng/artisan vendor:publish

                                                                                                 
  [Toplan\PhpSms\PhpSmsException]                                                                
  Please set at least one enable agent in config file(config/phpsms.php) or use method enable()  
                                                                                                 

Process finished with exit code 1 at 19:03:47.
Execution time: 89 ms.

**Comment by toplan** [comment]
请问是运行
```
php artisan vendor:publish
```
时候报的错？

**Comment by toplan** [comment]
在config/app.php文件中providers数组里加入：

```
Toplan\PhpSms\PhpSmsServiceProvider::class,
Toplan\Sms\SmsManagerServiceProvider::class,
```

**Comment by hawkefly** [comment]
你文档中写错了？
在config/app.php文件中providers数组里加入：

   Toplan\PhpSms\Sms::class,
   Toplan\Sms\SmsManagerServiceProvider::class,

**Comment by toplan** [comment]
是的，文档写错了，已经纠正，谢谢 :smile:

**Comment by hawkefly** [comment]
配置文件需要2个？一个laravel-sms,一个phpsms.

**Comment by hawkefly** [comment]
发语音验证码的时候，数据库表sms的data字段是空的。没记录验证码的值。

**Comment by toplan** [comment]
@hawkefly 配置文件两个，phpsms负责代理器配置，laraval-sms负责验证码模块的配置

**Comment by hawkefly** [comment]
我的意思是能不能合在一起的
