### ISSUE TITLE
Class 'Toplan\PhpSms\PhpSmsServiceProvide' not found 

### ISSUE THREAD

**Issue by kenfu** [toplan/laravel-sms#36]
尝试了所有版本，当php artisan vendor:publish 命令后。

Class 'Toplan\PhpSms\PhpSmsServiceProvide' not found 

错误。

LARAVEL 5.1.11

**Comment by toplan** [comment]
你好，你安装的哪个版本呢？
如果是1.0版本，需要把`Toplan\PhpSms\PhpSmsServiceProvide`去掉

**Comment by kenfu** [comment]
每个版本都尝试了，开始安装的是推荐版本，也是这个问题。

**Comment by toplan** [comment]
请复制这个
```php
Toplan\PhpSms\PhpSmsServiceProvider
```
文档中少写了一个r, 不好意思，感谢反馈

**Comment by kenfu** [comment]
https://github.com/toplan/laravel-sms/tree/l5

这个文档，安装方法：出现这个问题：
php artisan vendor:publish

[Toplan\PhpSms\PhpSmsException]                                                                
  Please set at least one enable agent in config file(config/phpsms.php) or use method enable()

**Comment by kenfu** [comment]
目前，我LARAVEL 5.1.11,想使用推荐版本，请问使用那个文档安装比较合适? PHP新手，最好能给一个手机注册的例子，比如FORM登陆框，我相信使用的人会很多。

**Comment by toplan** [comment]
@kenfu 就使用首页那个文档（是2.0版本的）
