### ISSUE TITLE
php artisan vendor:publish 后出现错误

### ISSUE THREAD

**Issue by kenfu** [toplan/laravel-sms#37]
按照首页教程，一步一步来，当进行到：

php artisan vendor:publish

出现以下错误：

[Toplan\PhpSms\PhpSmsException]                                                                
  Please set at least one enable agent in config file(config/phpsms.php) or use method enable()

**Comment by toplan** [comment]
恩，你按照报错的提示，在config/phpsms.php文件中写下配置就可以了：
```php
enable => [
  'Log'
]
```

**Comment by toplan** [comment]
在**配置**的三步：

* 设置代理器使用方案

请在config/phpsms.php中设置代理服务商。
```php
   'enable' => [
        //被使用概率为2/3
        'Luosimao' => '20',

        //被使用概率为1/3，且为备用代理器
        'YunPian' => '10 backup',
   ];
```

**Comment by kenfu** [comment]
关键是 使用 php artisan vendor:publish 后
config文件夹中没有生成 phpsms.php 文件

**Comment by kenfu** [comment]
麻烦楼主在新 laravel中一步一步安装测试下，看是不是我个人的问题。

**Comment by toplan** [comment]
我了解情况了，谢谢反馈，你先在vendor/toplan/phpsms/src/config/phpsms.php中这样写：
```php
   'enable' => [
     'Log'
  ]
```
这是个bug,我等会儿会发布修改后的2.0.6版本 :+1:

**Comment by kenfu** [comment]
期待，那我就等待2.0.6版本吧，楼主辛苦了！ 希望能给一个简单的登陆模板示例，谢谢！

**Comment by toplan** [comment]
@kenfu 2.0.6已发布，感谢的反馈！

**Comment by toplan** [comment]
模板示例稍晚给你写个
