### ISSUE TITLE
更改了默认的APP名字，测试时出现报错，应该是BUG

### ISSUE THREAD

**Issue by torome** [toplan/laravel-sms#41]
FatalErrorException in SendReminderSms.php line 12: Class 'App\Jobs\Job' not found

**Comment by toplan** [comment]
请问是否将app/Jobs文件夹下的Job抽象类的命名空间修改了吗？

**Comment by torome** [comment]
是的，通过命令批量更新的，所以app/Jobs的命名空间也是更改了xxx/Jobs

**Comment by toplan** [comment]
恩，了解了，我考虑的解决方案是，在config/laravel-sms.php中新加一项配置用来指定使用的队列任务job类，默认为`App\Jobs\SendReminderSms`，如果自己运行`php artisan app:name`或者自己想修改队列实现逻辑，则可以自己实现一个job类（Your\Namespace\YourJob），然后在配置中修改配置为`Your\Namespace\YourJob`。

当然如果有有更好方案，请告知 :smile:

**Comment by toplan** [comment]
https://github.com/toplan/laravel-sms#3-自定义队列job
