### ISSUE TITLE
访问 /sms/info 系统报错

### ISSUE THREAD

**Issue by OranTing** [toplan/laravel-sms#50]
访问 /sms/info 系统报错
根据帮助文件：
```
可以直接访问example.com/sms/info查看该模块是否可用，并可在该页面里观察验证码短信发送数据，方便你进行调试。
```
但是我访问example.com/sms/info  系统会报错。
![snip20160120_22](https://cloud.githubusercontent.com/assets/13476576/12441116/c8786f84-bf7e-11e5-8c84-f2276307ded4.png)

**Comment by OranTing** [comment]
The requested package toplan/laravel-sms ~2.2.4 could not be found   @toplan

**Comment by toplan** [comment]
@OranTing 请安装2.2.5
