### ISSUE TITLE
验证码短信模块 可否给个完整的Demo呢

### ISSUE THREAD

**Issue by OranTing** [toplan/laravel-sms#51]
验证码短信模块 
请求发送带验证码短信
到
服务器验证是否正确

有没有一个完整的demo呢？
小白，折腾了半天没成功。
谢谢。

**Comment by toplan** [comment]
你好，谢谢你的反馈，你提交的问题，为会在今天及时处理

**Comment by maxiaoxiong** [comment]
@toplan　@OranTing  我也等demo.
谢谢.

**Comment by gulipz** [comment]
我在等demo

**Comment by toplan** [comment]
请耐心等待下哈，我现在还在改进v2.4.0，可能还要花一两天改完，2.4.0比现在的`dev-master`版本还会有较大变动，届时会更加优雅的支持无session应用和动态验证规则

**Comment by XIONGchanghu** [comment]
@toplan 大大，现在支持laravel5.2了么？

**Comment by toplan** [comment]
@XIONGchanghu 大大不敢当哈，支持的

**Comment by XIONGchanghu** [comment]
@toplan 应该称大大，感谢你的努力开发出那么好的东西，有没有交流的群呢，大大

**Comment by toplan** [comment]
@XIONGchanghu  不客气，谢谢你的支持和鼓励，现在还没有qq群，我等下建一个

**Comment by XIONGchanghu** [comment]
@toplan 恩恩，3096949992，您拉我下哈，谢谢大大

**Comment by toplan** [comment]
各位童鞋，使用过程中有疑问的可以加群159379848交流哈
