### ISSUE TITLE
在做移动端服务器验证的时候，如果移动端没有将sessionID传过来，会导致422 confirm_mobile_not_change

### ISSUE THREAD

**Issue by LGC119** [toplan/laravel-sms#54]
咱们文档中的无会话支持也需要前端传过来sessionID吗，如果移动端没有传session ID会导致无法找到session缓存文件，从而导致验证错误。

**Comment by toplan** [comment]
如果是前后端完全分离（弃用session）的移动端，需要通过token来进行权限认证。

**Comment by LGC119** [comment]
我是按照文档描述的进行验证的，感觉是无法找到存token的session文件，所以没发进行比对
下面是我的验证规则，
![1a47ae35-4a65-42f4-b6ed-be88455814b9](https://cloud.githubusercontent.com/assets/7828027/12602372/cf9c7886-c4e3-11e5-9b5c-5d7934fa1d75.png)

**Comment by toplan** [comment]
嗯，你有没有实现自己的storage呢？

**Comment by toplan** [comment]
https://github.com/toplan/laravel-sms#3-服务端验证

**Comment by toplan** [comment]
![image](https://cloud.githubusercontent.com/assets/7815594/12602463/8493feee-c4e4-11e5-9be2-0cc8bec5add0.png)

**Comment by toplan** [comment]
如果弃用session, 那么需要自己实现一个存储器（比如使用redis）,实现起来也非常简单，这是例子：https://github.com/toplan/laravel-sms/blob/master/src/Toplan/LaravelSms/Storage/SessionStorage.php

**Comment by LGC119** [comment]
我明白了， 这部分配置我没有改，所以还是用的咱们自带的session方式，我刚刚把database_enable 设置为true，如果存数据库就不会有这个问题了吧

**Comment by toplan** [comment]
database_enable只是允许数据库纪录发送日志哦

**Comment by LGC119** [comment]
😅，好吧，那我还是去写个storage吧，多谢啦

**Comment by toplan** [comment]
嗯嗯，你先实现一个storage，三个方法：get,set,forget,你参照一下自带的SessionStorage吧，下个版本我会写一个RedisStorage

**Comment by LGC119** [comment]
好的！
