### ISSUE TITLE
希望增加支持 laravel 5.2 的版本

### ISSUE THREAD

**Issue by remxcode** [toplan/laravel-sms#57]
因为现在 5.2 的路由新增了 web 中间件，而此包内置的routes文件并没有启用 web 中间件，导致相关的 session 组件也没有启动，也就是说无法通过 session 存储，只有无会话方式才能正确调用。
官方文档的说明：https://laravel.com/docs/5.2/routing#basic-routing

**Comment by wyu-prc** [comment]
laravel 5.2可以用，修改以下两个文件内容，把laravel-sms的路由加到sms的中间件组中，在kernel中把web组加到sms里。对比一下就知道了：
**vendor/toplan/laravel-sms/src/Toplan/LaravelSms/routes.php**
Route::group(['middleware' => 'sms'], function () {
    Route::get('sms/info/{token?}', 'Toplan\Sms\SmsController@getInfo');
    Route::post('sms/verify-code', 'Toplan\Sms\SmsController@postSendCode');
    Route::post('sms/voice-verify', 'Toplan\Sms\SmsController@postVoiceVerify');
});

**app/Http/Kernel.php**
    protected $middlewareGroups = [
        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
        ],
        'api' => [
            'throttle:60,1',
        ],
        'sms' => [
            'web',
        ],
    ];

**Comment by remxcode** [comment]
嗯，我也是把 vendor/toplan/laravel-sms/src/Toplan/LaravelSms/routes.php  的内容，添加了web中间件, 使得其暂时能使用，但如果 laravel-sms 更新了，又没有添加5.2的兼容，本地修改的兼容代码就会被复写，所以还是需要适配5.2的版本

**Comment by iamike** [comment]
composer update 后重写route文件

**Comment by laraok** [comment]
这个程序很好啊。省事不少。

**Comment by zhangst911** [comment]
原则应该不动vendor里面的内容。
建议作者可以增加一个参数，设置route的middleware数组。

**Comment by Mianco** [comment]
确实，在开发中我也遵循这样的原则，尽量不改动vendor里面的代码。没想到laravel的5.1和5.2区别还蛮大的。

**Comment by jnuc093** [comment]
看来5.2的需求还挺多!

**Comment by toplan** [comment]
已经在处理中，顺便在优化代码，因为处理过程中看之前代码感觉各种不顺眼就想改进，但最近太忙，做得断断续续的，各位体谅下，会尽快处理的

**Comment by jackypu** [comment]
@toplan 搬个凳子安静的等待，我也是不想改vendor的代码。

**Comment by toplan** [comment]
@jackypu 😄 明天会更新

**Comment by toplan** [comment]
已经跟新到`dev-master`，各位可以先尝试下，改动比较多，我明天还有测试下， 这个isssue的解决方案采纳了 @zhangst911 的建议，谢谢！

**Comment by iamike** [comment]
请问阿里大鱼支持吗？

**Comment by toplan** [comment]
@iamike 阿里大鱼的接口发生了变动，我需要更新phpsms的代码，请耐心等待下

**Comment by iamike** [comment]
谢谢，辛苦啦

**Comment by toplan** [comment]
@iamike `dev-master`已更新，可以先用`dev-master`体验下，大家体验下感觉满意了，我就打包2.4.0

**Comment by toplan** [comment]
已发布2.4.0
