### ISSUE TITLE
Don`t found driver [] in task [PhpSms], please define it for current task

### ISSUE THREAD

**Issue by yaoshanliang** [toplan/laravel-sms#59]
`php artisan queue:listen`之后提示`Don`t found driver [] in task [PhpSms], please define it for current task`

**Comment by toplan** [comment]
你好，请问你在配置文件config/phpsms.php中配置可用代理器没有？

**Comment by yaoshanliang** [comment]
配置了，配置了luosimao的，然后`'enable' => ['Luosimao' => '20 backup']`

**Comment by yaoshanliang** [comment]
@toplan 
错误日志`Toplan\TaskBalance\Task->runDriver(NULL)`
* task-balancer下Task.php文件run方法中参数$driverName为空，执行`$driverName = $this->getDriverNameByWeight();`
* getDriverNameByWeight中$this->drivers为空，执行return $this->driverNameRand();
* driverNameRand中$this->drivers还是空的，就return了

**Comment by toplan** [comment]
嗯，根据报错是说没有代理器，你通过`PhpSms::getEnableAgents()`方法看看读取到代理器没

**Comment by yaoshanliang** [comment]
有的，和我配置的一样，array:1 [ "Luosimao" => "20 backup"]

**Comment by toplan** [comment]
嗯，那就太奇怪了，是通过队列，直接发送也是这个错误吗？

**Comment by yaoshanliang** [comment]
加上PhpSms::queue(false);后直接发送正常。

**Comment by toplan** [comment]
你使用的什么队列系统呢？

**Comment by yaoshanliang** [comment]
@toplan redis

**Comment by mani95lisa** [comment]
@toplan 同样的问题，也是用的redis呢

**Comment by toplan** [comment]
@yaoshanliang @mani95lisa 该问题已解决，请更新版本到v2.3.1
