### ISSUE TITLE
Class 'Toplan\PhpSms\Facades\Sms' not found

### ISSUE THREAD

**Issue by xzpeng** [toplan/laravel-sms#60]
Laravel5.2
laravel-sms v2.2.6

在本地Mac运行正常，可以发送短信，但是在Ubuntu系统报错: 

- ErrorException in AliasLoader.php line 66:
- Class 'Toplan\PhpSms\Facades\Sms' not found

然后检查了一下:
- var_dump(class_exists('Toplan\PhpSms\Facades\Sms'));
- var_dump(class_exists('Toplan\Sms\Facades\SmsManager'));

输出:
- bool(false) bool(true)

代码是完全一样的，有没有人遇到过这问题？
可能是什么原因导致的呢？目录名字大小写？

**Comment by abcn** [comment]
我这边也遇到了相同的问题

**Comment by yaoshanliang** [comment]
我也是，好好的就不行了，怎么解决

**Comment by yaoshanliang** [comment]
我的laravel5.1

**Comment by xzpeng** [comment]
可能是psr4规范的原因，
在laravem-sms里加了条路由，临时应对一下 -_#

**Comment by toplan** [comment]
![image](https://cloud.githubusercontent.com/assets/7815594/14196583/88be8a38-f7f8-11e5-9c05-72c6f9f46f1d.png)

**Comment by toplan** [comment]
![image](https://cloud.githubusercontent.com/assets/7815594/14196604/d22c19f6-f7f8-11e5-8039-507261c2fc78.png)

难道是需要单独写facades的规则？"Toplan\\PhpSms\\Facades":  ["src/phpsms/facades"]

**Comment by yaoshanliang** [comment]
怎么解决呀～～

**Comment by toplan** [comment]
待会儿会更新phpsms v1.2.3以期解决该问题

**Comment by toplan** [comment]
@yaoshanliang 已更新phpsms v1.2.3解决该问题

**Comment by toplan** [comment]
@xzpeng @abcn @yaoshanliang 该问题已解决，请使用最新版本v2.3.1
