### ISSUE TITLE
是我的姿势不对吗?.... ie8下,js报错.  

### ISSUE THREAD

**Issue by xjdata** [toplan/laravel-sms#68]
chrome等都好好的, 就是ie8, 加载后就会出错. 呃... 当前界面没有

``` js
        var opts = $.extend(
            $.fn.sms.default,
            options
        );
```

报错是这个 `$.fn.sms.default,`.
打开ie8的调试台, 显示  缺少标识符   点击后  光标聚焦到 sms.这里....

**Comment by toplan** [comment]
能否截个图呢？

**Comment by xjdata** [comment]
![qq 20160420134114](https://cloud.githubusercontent.com/assets/4524983/14664454/be211600-06fd-11e6-895a-48cf76244ba2.png)
![qq 20160420134207](https://cloud.githubusercontent.com/assets/4524983/14664455/bf90d476-06fd-11e6-8d0b-78fed1ff6246.png)

**Comment by xjdata** [comment]
环境是 虚拟机 xp  啥都没装 就一个ie8   自动更新了几个补丁.

**Comment by HiYangZhi** [comment]
我在IE8下也遇到了这个问题

**Comment by toplan** [comment]
用最新版试试
