### ISSUE TITLE
云通讯发送成功返回没有statusMsg属性

### ISSUE THREAD

**Issue by GuafengLin** [toplan/laravel-sms#69]
云通讯发送短信成功返回的$result
不存在statusMsg属性。
会报以下错误
Undefined property: stdClass::$statusMsg

"line":78,"file":"/vendor\/toplan\/phpsms\/src\/phpsms\/agents\/YunTongXunAgent.php",

**Comment by toplan** [comment]
该问题已在到[phpsms](https://github.com/toplan/phpsms)处理了
