### ISSUE TITLE
2.3.1还不支持阿里大鱼吧

### ISSUE THREAD

**Issue by wh469012917** [toplan/laravel-sms#71]
我看了下代码。都没有和阿里大鱼相关的

**Comment by toplan** [comment]
是由[phpsms](https://github.com/toplan/phpsms)提供的哦，更新phpsms到1.5.0就支持了，活着等我明天统一更新

**Comment by wh469012917** [comment]
@toplan ok,那今天更新会支持5.2吗

**Comment by wh469012917** [comment]
@toplan 问下怎么更新phpcms呢？直接修改composer.json吗

**Comment by toplan** [comment]
可以先安装`dev-master`， 2.4.0会在这两天打包

**Comment by toplan** [comment]
dev-master已更新，解决该问题，请等待发布2.4.0
