### ISSUE TITLE
2.4的包还没传到packagist吧，提示该版本存在

### ISSUE THREAD

**Issue by wh469012917** [toplan/laravel-sms#77]

**Comment by jnuc093** [comment]
好像是的还没有上传
尝试安装 composer require 'toplan/laravel-sms:dev-master' 但是也没成功。

**Comment by toplan** [comment]
有bug,刚刚跟新了下，`dev-master`版本可以安装了，可以尝试使用下，因为改动比较大，等我测试完了再打发2.4

**Comment by jnuc093** [comment]
辛苦 辛苦

**Comment by toplan** [comment]
我现在还在改进v2.4.0，可能还要花一两天改完，2.4.0比现在的dev-master版本还会有较大变动，届时会更加优雅的支持无session应用和动态验证规则

**Comment by toplan** [comment]
已发布
