### ISSUE TITLE
ErrorException in YunTongXunAgent.php line 77: Undefined property: stdClass::$statusMsg

### ISSUE THREAD

**Issue by peirenlei** [toplan/laravel-sms#85]
以下代码会报错，但是短信可以收到
~~~php

$templates = [
    'YunTongXun' => '1',
    'SubMail' => '1'
];

$tempData = [
    'code' => '87392',
    'minutes' => '5'
];

PhpSms::make()->to($to)->template($templates)->data($tempData)->send();

~~~
ErrorException in YunTongXunAgent.php line 77: Undefined property: stdClass::$statusMsg

**Comment by peirenlei** [comment]
YunTongXunAgent.php line 77 修改为：
$info = property_exists($result,'statusMsg') ? (string) $result->statusMsg : 'SendSuccess';

**Comment by toplan** [comment]
已处理：https://github.com/toplan/phpsms/pull/69/files
