### ISSUE TITLE
阿里大鱼发送失败

### ISSUE THREAD

**Issue by gewuxy** [toplan/laravel-sms#91]
有发送成功的吗，我按照配置，用js,发送报错：TEMPLATE_MISSING_PARAMETERS

**Comment by toplan** [comment]
阿里大鱼的模版里需要有code参数

**Comment by gewuxy** [comment]
还有哪里需要配置或者代码哪里要修改吗？我clone 的是2.4.*

**Comment by gewuxy** [comment]
成功了，修改minute为product

**Comment by toplan** [comment]
@gewuxy 你好，你是直接修改的源代码嘛？我建议能否常识把阿里大鱼模版中的`product`改为`minute`
