### ISSUE TITLE
怎么validation.php中适配错误提示

### ISSUE THREAD

**Issue by gewuxy** [toplan/laravel-sms#92]
'custom' => [
        'phone' => [
	        'mobile_required' => '请填写手机号码',
        ],
]
这个规则无效；
'custom' => [
        'phone' => [
	        'mobile_required.required' => '请填写手机号码',
        ],
]
也无效。
请问怎么添加规则呢？

**Comment by gewuxy** [comment]
已解决

**Comment by fmwww** [comment]
想问下怎么解决的？

**Comment by fmwww** [comment]
解决了
