### ISSUE TITLE
confirm_rule:mobile,mobile_required是什么意思

### ISSUE THREAD

**Issue by gewuxy** [toplan/laravel-sms#93]
confirm_rule:mobile,mobile_required是应用mobile_required规则吗？
我在validation文件中应用
'mobile' => [
			'unique'   => '手机号码已经注册，请直接登录',
			'required' => '请填写手机号码',
			'zh_mobile' => '手机号码格式错误',
			'confirm_rule' => '手机号码前后不一致',
        ],
后一直提示手机号码前后不一致；

放在：
'verifyCode' =>[
			'required'   => '请输入验证码',
			'verify_code' => '验证码错误',
			'confirm_rule' => '手机号码前后不一致',
		],
这里又一直提示validation.confirm_rule

**Comment by toplan** [comment]
confirm_rule:mobile,mobile_require 的意思是检测验证mobile参数的规则是'mobile_required'

**Comment by toplan** [comment]
但是我突然觉得，我这里设计得不合理，我现在来设计的话，我会改成这样：
```php
'mobile' => 'confirm_mobile_not_change|confirm_rule:mobile_required'
```

**Comment by gewuxy** [comment]
报validation.confirm_rule错误啊

**Comment by gewuxy** [comment]
return Validator::make($data, [
            'mobile' => 'required|unique:users|confirm_rule:mobile_required|confirm_mobile_not_change',
            'verifyCode' => 'required|verify_code',
            'password' => 'required|confirmed|min:6',
        ]);

**Comment by gewuxy** [comment]
我没修改手机号码，实际是不应该报错的

**Comment by gewuxy** [comment]
我没修改手机号码，实际是不应该报错的

**Comment by toplan** [comment]
return Validator::make($data, [
            'mobile' => 'required|unique:users|confirm_rule:mobile,mobile_required|confirm_mobile_not_change',
            'verifyCode' => 'required|verify_code',
            'password' => 'required|confirmed|min:6',
        ]);

**Comment by toplan** [comment]
还有，在发送短信时mobile参数的验证方式，你使用的是'mobile_required'吗？

**Comment by toplan** [comment]
confirm_rule已经修改 https://github.com/toplan/laravel-sms#confirm_rulerulename
