### ISSUE TITLE
最新2.4版本未适配5.1 

### ISSUE THREAD

**Issue by shjchen** [toplan/laravel-sms#98]
5.1作为LTS版本，在我们公司已经作为项目的开发环境，而且在近期内都不会去升级到5.2的版本。

目前在2.4版本中，作者默认使用了web Middleware ，这样导致在5.1版本中是无法使用的。除非我们去修改代码。

建议作者需要去考虑适配5.1 的版本。

**Comment by toplan** [comment]
@shjchen 计划中哈，最近在找工作，耽搁了

**Comment by shjchen** [comment]
恩，辛苦了。可以搞个捐赠的通道出来，很多人都会支持的。目前这一块国内的氛围慢慢好起来了。
